export const JOBS_REQUESTED = "JOBS_REQUESTED";
export const JOBS_REQUESTED_FAILED = "JOBS_REQUESTED_FAILED";
export const JOBS_REQUESTED_EMPTY = "JOBS_REQUESTED_EMPTY";
export const JOBS_RECEIVED = "JOBS_RECEIVED";
export const JOB_DETAILS_RETRIEVED = "JOB_DETAILS_RETRIEVED";
