export const JOBS_REQUESTED = "JOBS_REQUESTED";
export const JOBS_REQUESTED_FAILED = "JOBS_REQUESTED_FAILED";
export const JOBS_RECEIVED = "JOBS_RECEIVED";
export const SEARCHED_JOB_RECEIVED = "SEARCHED_JOB_RECEIVED";
